CREATE DATABASE College_Student;
CREATE DATABASE IF NOT EXISTS College_Student;

DROP DATABASE IF EXISTS Company_Data;
USE College_Student;

CREATE TABLE Student (
ID INT PRIMARY KEY,
NAME VARCHAR (100),
GENDER VARCHAR(60),
ADDRESS VARCHAR (100),
AGE INT NOT NULL
);

INSERT INTO Student VALUES(1, "DHRUBARAJ", "MALE", "KOLKATA", 22);
INSERT INTO Student VALUES(2, "AKASH", "MALE", "KOLKATA", 20);
INSERT INTO Student VALUES(3, "ASOKE", "MALE", "KOLKATA", 21);
INSERT INTO Student VALUES(4, "AVI", "MALE", "KOLKATA", 18);

SELECT * FROM Student;